### ISSUE TITLE
Fixed Frame : No tf data.

### ISSUE THREAD

**Issue by CCCCe** [robo-friends/m-explore-ros2#17]
I can run the procedure successfully and see the result in .rviz film.  But  I can't observe the process of merging. In rviz2, robot1/map and robot2/map can be seen . When I open tf view, it only one word : no tf data

**Comment by charlielito** [comment]
Are you using the provided `/map_merge/launch/map_merge.rviz` ?

**Comment by CCCCe** [comment]
> Are you using the provided `map_merge/launch/map_merge.rviz` ?

I mean, in ROS, we can use web to subscribe the topic /map to get information about result of map. and it is suitable for ROS2 with foxy-rosbridge?

**Comment by charlielito** [comment]
I don't see why it shouldn't be suitable for rosbridge if you are able to see it in rviz2. I still don't get what is not working for you. Can you please add more details? What steps did you follow and what is not working?

**Comment by CCCCe** [comment]
> I don't see why it shouldn't be suitable for rosbridge if you are able to see it in rviz2. I still don't get what is not working for you. Can you please add more details? What steps did you follow and what is not working?

Well，I will list the steps I did:
1.followed Readme, I can see the the procession of map_merging in order rviz -d workspace/src/m-explore-ros2/map_merge/launch/map_merge.rviz.
2.I tried to see the result in another window opening with rviz2, and then, I found it reported : no data received
3. this is my a thinking. I try to use web to receive map like ROS1 using rosbridge, but it didn't show the map like ROS1.

**Comment by charlielito** [comment]
If the 1. step is working but 2. is not then it is likely to be a problem from your setup in that rviz.
Remember that the merged map is published in the `world_frame` frame which is a parameter of this package and by default it is "world".  To be able to see that topic you need to set in rviz the global frame to `world`
![Screenshot from 2022-07-04 19-18-59](https://user-images.githubusercontent.com/8033598/177227884-a5aac19e-2c78-4cb7-bb5e-4a96b727a1ed.png)

Closing this since it is not a problem from this package
