### ISSUE TITLE
Using m-explore with RTAB-Map

### ISSUE THREAD

**Issue by hmatatagi** [robo-friends/m-explore-ros2#32]
Hello,

I was wondering if it would be possible to use m-explore with RTAB-Map. And if it is possible, how can I use it? As far as I know, RTAB-Map publishes nav_msgs/msg/OccupancyGrid message to the /map topic. However, when I launch explore.launch.py, I just get "Waiting for costmap to become available, topic: map" in the terminal, and nothing else happens. I double-checked the source code, and it looks like the costmap_client node is subscribed to a topic with a type of nav_msgs/msg/OccupancyGrid, so I am confused as to why it is not working. I am currently using Humble. Any help or advice is greatly appreciated. Thank you in advance!

**Comment by charlielito** [comment]
According to their [RTAB-Map docs](http://wiki.ros.org/rtabmap_ros) they produce **indeed** a 2D Map so that is not the issue.

@hmatatagi  an you share the output of `ros2 topic info --verbose /map` to see if our node is subscribed or if it might be some QoS incompatibility issue

A rosbag could also help us debug the problem. Without additional information, it is very difficult to know what might be happening
